
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: DoctorAPI_development


test:
  <<: *default
  database: DoctorAPI_test


production:
  <<: *default
  database: DoctorAPI_production
  username: DoctorAPI
  password: <%= ENV['DOCTORAPI_DATABASE_PASSWORD'] %>
