# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9279c18df99f5c6ab5bdc6961ca4db3c2c7d5991f864ffcea3e6428fd714684186ded748ea2fe3f44e0e302699728d4fd61d14271ef86b083b85469716af1b9e

test:
  secret_key_base: 8bc151cadf5207aaeab9ce6cb5aa85a2e06a440faf60109cbb6c727635ff368f0acaf498e2a72f7a6917709cb4f80154483e98c0e1677cbc2cbee93a409422bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
